[package]
name = "odoo-app"
version = "0.1.0"
edition.workspace = true

[dependencies]
odoo-core = { path = "../odoo-core" }
odoo-modules = { path = "../odoo-modules" }
odoo-sqlite = { path = "../odoo-sqlite" }
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
ureq = { version = "2", features = ["json"] }
lettre = { version = "0.11", default-features = false, features = ["smtp-transport", "builder", "hostname", "rustls-tls", "ring", "webpki-roots"] }
odoo-duckdb = { path = "../odoo-duckdb", optional = true }
odoo-postgres = { path = "../odoo-postgres", optional = true }
odoo-mysql = { path = "../odoo-mysql", optional = true }

[features]
duckdb = ["dep:odoo-duckdb"]
postgres = ["dep:odoo-postgres"]
mysql = ["dep:odoo-mysql"]
