[package]
name = "odoo-server"
version = "0.1.0"
edition.workspace = true

[dependencies]
odoo-app = { path = "../odoo-app" }
odoo-core = { path = "../odoo-core" }
serde.workspace = true
serde_json.workspace = true
axum = "0.8"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"] }
tower-http = { version = "0.6", features = ["cors"] }
